### PR TITLE
handle invalid severity value & provide friendly error message

### LINKED ISSUE #190: bgColor is not a function when using invalid severity value
**Describe the bug**

When running `openapi lint main`, I get this error. when I have an invalid severity value:

```
TypeError: bgColor is not a function
    at formatCodeframe (/Users/adam/Projects/Redocly/openapi-demo/node_modules/@redocly/openapi-cli/lib/format/format.js:87:33)
    at Object.formatProblems (/Users/adam/Projects/Redocly/openapi-demo/node_modules/@redocly/openapi-cli/lib/format/format.js:41:41)
    at /Users/adam/Projects/Redocly/openapi-demo/node_modules/@redocly/openapi-cli/lib/cli.js:105:26
    at Generator.next (<anonymous>)
    at fulfilled (/Users/adam/Projects/Redocly/openapi-demo/node_modules/@redocly/openapi-cli/lib/cli.js:6:58)
```

**To Reproduce**
1. Given this `.redocly.yaml` file (see snippet below) that has "warning" instead of "warn"
2. And running `openapi lint main`.
4. See error pasted above.

The same happens with any unexpected value for `severity` such as `foo`.

**Expected behavior**
A more friendly error message, such as "Invalid severity level; accepted values: `error` or `warn`".

**OpenAPI definition**
n/a

**Version(s)**
- 1.0.0-beta.9

**Additional context**

## `.redocly.yaml` file snippet
```
apiDefinitions:
  main: openapi/external.yaml
lint:
  extends:
    - recommended
  plugins:
    - './plugins/demo-plugin.js'
  rules:
    demo/response-contains-property: 
      severity: warning
```

### PR DESCRIPTION
**Pull request by andriyl**
Closes #190

### CODE REVIEW

File: src/format/format.ts [hunk 1]
```diff
@@ -14,6 +14,10 @@ import { NormalizedProblem, ProblemSeverity, LineColLocationObject, LocationObje
 import { getCodeframe, getLineColLocation } from './codeframes';
 import { Totals } from '../cli';
 
+const ERROR = {
```
Comment (RomanHotsiy) [inline src/format/format.ts:17]: I would rename to:

```suggestion
const ERROR_MESSAGES = {
```

But is there a point to have it separately? It is not reused anywhere. I'm okay to keep it though.

**Review by RomanHotsiy — CHANGES_REQUESTED** [review]
LGTM 👍

There is just a small change request.

**Review by RomanHotsiy — APPROVED** [review]
