### PR TITLE
fix: no-invalid-media-type-examples doesn't work with example that uses

### LINKED ISSUE #518: no-invalid-media-type-examples doesn't work with example that uses $ref
**Describe the bug**

It reports:

Example value must conform to the schema: must NOT have additional properties `$ref`.

```
16 |         $ref: '../components/schemas/Schema.yaml'
17 |       example:
18 |         $ref: '../components/examples/example.yaml'
             ^^^^
```

**To Reproduce**

Use $ref to an external file in the example.

**Expected behavior**
Should work.

### PR DESCRIPTION
**Pull request by andriyl**
## What/Why/How?
Closes #518 

## Check yourself
- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [x] All new/updated code is covered with tests

## Security
- [x] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### CODE REVIEW

File: packages/core/src/rules/oas3/no-invalid-media-type-examples.ts [hunk 1]
```diff
@@ -13,31 +13,27 @@ export const ValidContentExamples: Oas3Rule = (opts) => {
...
+          for (const exampleName of Object.keys(mediaType.examples)) {
+            resolveAndValidateExample(mediaType.examples[exampleName], location.child(['examples', exampleName, 'value']), true);
+          }
+        }
+
+        function resolveAndValidateExample(example: Oas3Example | any, location: Location, isMultiple?: boolean) {
+          if (isRef(example)) {
+            const resolved = resolve<Oas3Example>(example);
+            if (!resolved.location) return;
+            location = resolved.location.child('value');
```
Comment (RomanHotsiy) [inline packages/core/src/rules/oas3/no-invalid-media-type-examples.ts:27]:
```suggestion
            location = isMultiple ? resolved.location.child('value') : resolved.location;
```

File: __tests__/lint/no-invalid-media-type-examples/openapi.yaml [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+      requestBody:
+        content:
+          application/json:
+            schema:
+              type: object
+              properties:
+                property:
+                  type: string
+            example:
+              $ref: '#/components/examples/State'
```
Comment (RomanHotsiy) [inline __tests__/lint/no-invalid-media-type-examples/openapi.yaml:24]: Add one more tests that tests bad example to verify it reports location correctly. Thanks!

**Review by RomanHotsiy — CHANGES_REQUESTED** [review]

**Review by RomanHotsiy — APPROVED** [review]
